- 👋 Olá eu sou @IlluminatiFurioso
- 👀 Tenho interesse em Dublagem e Jogos ...
- 🌱 Atualmente estou estudando Programação e Dublagem através do youtube ...
- 🤔 Eu tenho esse nome meio estranho aqui, mas o meu verdadeiro nome é Richard Pablo ...
- 🏠 Moro no Brasil, sou do estado do Paraná em uma cidade chamada Carlópolis ...
- 🎞 Tenho um canal no youtube, é por isso que eu tenho esse nome estranho aqui kkk ...
<!---
IlluminatiFurioso/IlluminatiFurioso is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
